### ISSUE TITLE
pdf编译的时候没带字体

### ISSUE THREAD

**Issue by Yangff** [txyyss/Lambda-Calculus#1]
标题的意思。。

**Comment by txyyss** [comment]
所以你没法编译是吧？所以我提供了编译好的 PDF  文件了啊。
或者你可以自己改一下字体：

\setmainfont{Minion Pro}
\setmonofont{Source Code Pro}
\pagestyle{plain}
\punctstyle{kaiming}
\setmathfont{Asana Math}

上面一共用到了 Minion Pro 做英文正文字体，Source Code Pro 做代码字体，Asana Math 做数学字体，你可以统统改掉，或者注释掉看看。此外，文件第一行的

\documentclass[a4paper,adobefonts]{ctexart}

表示用了 Adobe Reader 自带的宋体楷体黑体作为中文正文字体，也是需要你自己先装在系统里，你也可以把 adobefonts 给去掉了再编译。

你看这么改下来是不是就可以编译了，要是编译没问题的话告诉我一声，我这就可以把这个 Issue 关掉了。

这些字体都有版权的啦，我嵌在 PDF 里面没问题，放在代码库里就不好了。
