### ISSUE TITLE
关于第11页解释器里的对于Fact的定义

### ISSUE THREAD

**Issue by xuewei4d** [txyyss/Lambda-Calculus#3]
Lambda> FACT = \n.IF (ISZERO n) ONE (MULT ONE (FACT (PRED n)))

是不是应该是

Lambda> FACT = \n.IF (ISZERO n) ONE (MULT n (FACT (PRED n)))

**Comment by txyyss** [comment]
已经修改好，并更新了 PDF 文件。请查验。

非常感谢你的仔细啦。虽然没有本质的影响，但不一致确实得改过来。
